import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../component/Footer";
import Navbar from "../component/Navbar";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${albertSans.variable} antialiased`}>
        {/* GLOBAL BACKGROUND */}
        <div className="grid-background" />
        <div className="cursor-spotlight" />

        {/* FLOATING SHAPES */}
        <div className="shape-decoration shape-1" />
        <div className="shape-decoration shape-2" />
        <div className="shape-decoration shape-3" />
        <div className="shape-decoration shape-4" />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
